jobs:
  check_java11:
    name: Java 11
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 11
    - continue-on-error: true
      name: Gradle cache
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-gradle-jdk11-${{ hashFiles('**/*.gradle*') }}
        path: '~/.gradle/caches

          ~/.gradle/wrapper

          '
        restore-keys: '${{ runner.os }}-gradle-jdk11

          '
    - continue-on-error: true
      name: Compile with Gradle
      run: ./gradlew assemble
    - continue-on-error: true
      name: Test
      run: ./gradlew check
    - continue-on-error: true
      name: Code coverage
      uses: codecov/codecov-action@v3
    - continue-on-error: true
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: always() && env.SLACK_WEBHOOK_URL
      name: Slack Notification
      uses: 8398a7/action-slack@v3
      with:
        author_name: Java 11 Build/Test
        custom_payload: "{\n  attachments: [{\n    color: '${{ job.status }}' ===\
          \ 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',\n\
          \    text: `${process.env.AS_WORKFLOW} -- (${process.env.AS_COMMIT}) of\
          \ ${process.env.AS_REPO}@${{ github.head_ref || github.ref }} by ${process.env.AS_AUTHOR}\
          \ ${{ job.status }} in ${process.env.AS_TOOK}`,\n  }]\n}\n"
        fields: workflow,commit,repo,author,took
        job_name: Java 11
        status: custom
  check_java_latest:
    name: Java 17
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 17
    - continue-on-error: true
      name: Gradle cache
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-gradle-jdk17-${{ hashFiles('**/*.gradle*') }}
        path: '~/.gradle/caches

          ~/.gradle/wrapper

          '
        restore-keys: '${{ runner.os }}-gradle-jdk17

          '
    - continue-on-error: true
      name: Compile with Gradle
      run: ./gradlew assemble
    - continue-on-error: true
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: always() && env.SLACK_WEBHOOK_URL
      name: Slack Notification
      uses: 8398a7/action-slack@v3
      with:
        author_name: Java 17 Build
        custom_payload: "{\n  attachments: [{\n    color: '${{ job.status }}' ===\
          \ 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',\n\
          \    text: `${process.env.AS_WORKFLOW} -- (${process.env.AS_COMMIT}) of\
          \ ${process.env.AS_REPO}@${{ github.head_ref || github.ref }} by ${process.env.AS_AUTHOR}\
          \ ${{ job.status }} in ${process.env.AS_TOOK}`,\n  }]\n}\n"
        fields: workflow,commit,repo,author,took
        job_name: Java 17
        status: custom
on:
  repository_dispatch:
    types: trigger-ga___ci-build-test.yml
