jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 11
    - continue-on-error: true
      name: Gradle cache
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-gradle-jdk11-${{ hashFiles('**/*.gradle*') }}
        path: '~/.gradle/caches

          ~/.gradle/wrapper

          '
        restore-keys: '${{ runner.os }}-gradle-jdk11

          '
    - continue-on-error: true
      name: Create Artifacts
      run: './generate_samples.sh

        # delete uncompressed output, sample zips are in ./samples/

        rm -rf output/

        ./gradlew uberJar javadoc graphviz

        mkdir -p output/build/javadoc

        mv build/docs/javadoc/* output/build/javadoc

        '
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Delete Previous master-branch-latest Tag
      uses: dev-drprasad/delete-tag-and-release@v0.2.1
      with:
        delete_release: true
        tag_name: master-branch-latest
    - continue-on-error: true
      id: create_release
      name: Create Release
      uses: ncipollo/release-action@v1
      with:
        draft: false
        prerelease: true
        tag: master-branch-latest
        token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Deploy UberJar
      uses: actions/upload-release-asset@v1
      with:
        asset_content_type: application/java-archive
        asset_name: synthea-with-dependencies.jar
        asset_path: build/libs/synthea-with-dependencies.jar
        upload_url: ${{ steps.create_release.outputs.upload_url }}
    - continue-on-error: true
      name: Publish Release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        omitBodyDuringUpdate: true
        replacesArtifacts: false
        tag: master-branch-latest
        token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        commit_message: rebuild graphs, javadoc and binary distribution at
        enable_jekyll: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
        keep_files: true
        publish_dir: ./output
        user_email: jwalonoski@mitre.org
        user_name: Jason Walonoski
    - continue-on-error: true
      env:
        SSH_DEPLOY_KEY: ${{ secrets.PUSH_SAMPLE_DATA_SSH_KEY }}
      name: Push samples to sample repo
      uses: cpina/github-action-push-to-another-repository@main
      with:
        destination-github-username: synthetichealth
        destination-repository-name: synthea-sample-data
        source-directory: samples
        target-branch: main
        target-directory: downloads/latest
    - continue-on-error: true
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: failure()
      name: Slack Notification on Failure
      uses: 8398a7/action-slack@v3
      with:
        author_name: Deploy Workflow
        custom_payload: "{\n  attachments: [{\n    color: 'danger',\n    text: `${process.env.AS_WORKFLOW}\
          \ -- (${process.env.AS_COMMIT}) of ${process.env.AS_REPO}@master by ${process.env.AS_AUTHOR}\
          \ ${{ job.status }} in ${process.env.AS_TOOK}`,\n  }]\n}\n"
        fields: workflow,commit,repo,author,took
        job_name: Deploy
        status: custom
on:
  repository_dispatch:
    types: trigger-ga___deploy.yml
